---
- name: Ensure python3 is installed (Debian)
  action: apt pkg=python3 state=present
  when: ansible_os_family == 'Debian'
#to test
- name: Ensure python3 is installed (RedHat).
  yum: name=python3 state=installed
  when: ansible_os_family == 'RedHat'

- name: "create aws conf dir"
  file:
    path: "/root/.aws"
    state: "directory"
    mode: 0700
    owner: root
    group: root
- name: add route53 credentials to VM
  blockinfile:
    path: /root/.aws/credentials
    owner: root
    group: root
    mode: 0600
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK aws-internal-dns"
    block: |
      [aws-internal-dns]
      aws_access_key_id = {{ aws_dns_access_key_id }}
      aws_secret_access_key = {{ aws_dns_secret_access_key }}
- name: "Copy AWS cli53 binary"
  get_url:
    url: "https://github.com/barnybug/cli53/releases/download/{{ aws_dns_client_version }}/cli53-linux-amd64"
    dest: /usr/local/bin/cli53
    owner: root
    group: root
    mode: 0700
    force: "{{ aws_dns_force_redeploy_cli53_binary }}"
- name: "Copy DNS update script"
  template:
    src: awsInternaldnsUpdate.py
    dest: /usr/local/bin/awsInternaldnsUpdate.py
    owner: root
    group: root
    mode: 0700
- name: "Copy unitd stop"
  copy:
    src: awsInternaldnsUpdateStop.service
    dest: /etc/systemd/system/awsInternaldnsUpdateStop.service
    owner: root
    group: root
    mode: 0644
  notify: "reload systemd"
- name: "Copy unitd start"
  template:
    src: awsInternaldnsUpdateStart.service
    dest: /etc/systemd/system/awsInternaldnsUpdateStart.service
    owner: root
    group: root
    mode: 0644
  notify: "reload systemd"

- name: "enable systemd unit"
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - awsInternaldnsUpdateStop.service
    - awsInternaldnsUpdateStart.service
